services:
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  postgres:
    image: postgres:17-alpine
    restart: always
    env_file:
      - backend/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: uvicorn app.server.main:create_app --host 0.0.0.0 --port 8000 --reload --factory
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/api/v1/healthcheck || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - bot/.env
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./bot/logs:/app/logs

volumes:
  postgres_data:
  redis_data:
